import Foundation

/// A curated embedded thesaurus of common English words with practical,
/// commonly-used synonyms (comparable to Microsoft Word's thesaurus quality).
/// For uncommon words, the app falls back to online APIs.
struct EmbeddedThesaurus {
    static let data: [String: [String]] = [
        // A
        "abandon": ["leave", "desert", "forsake", "relinquish", "discard", "quit", "surrender", "ditch"],
        "ability": ["skill", "talent", "capacity", "capability", "aptitude", "competence", "proficiency", "expertise"],
        "able": ["capable", "competent", "skilled", "qualified", "proficient", "adept", "talented"],
        "abolish": ["eliminate", "end", "eradicate", "annul", "revoke", "cancel", "scrap", "repeal"],
        "about": ["approximately", "roughly", "around", "nearly", "close to", "regarding", "concerning"],
        "above": ["over", "higher", "beyond", "overhead", "atop", "exceeding", "surpassing"],
        "absent": ["missing", "away", "gone", "unavailable", "lacking", "elsewhere"],
        "absorb": ["soak", "take in", "assimilate", "consume", "engross", "immerse", "occupy"],
        "abstract": ["theoretical", "conceptual", "intangible", "notional", "hypothetical"],
        "absurd": ["ridiculous", "ludicrous", "preposterous", "nonsensical", "foolish", "silly", "farcical"],
        "abundant": ["plentiful", "ample", "copious", "profuse", "lavish", "bountiful", "rich"],
        "abuse": ["mistreat", "exploit", "misuse", "maltreat", "harm", "wrong", "damage"],
        "accept": ["receive", "take", "embrace", "acknowledge", "approve", "agree", "consent", "admit"],
        "accomplish": ["achieve", "complete", "fulfill", "attain", "finish", "execute", "realize", "perform"],
        "accurate": ["precise", "exact", "correct", "right", "true", "faithful", "reliable", "spot-on"],
        "accuse": ["blame", "charge", "indict", "allege", "implicate", "denounce", "incriminate"],
        "achieve": ["accomplish", "attain", "reach", "fulfill", "complete", "realize", "obtain", "earn"],
        "acknowledge": ["admit", "recognize", "accept", "concede", "confess", "grant", "appreciate"],
        "acquire": ["obtain", "get", "gain", "procure", "secure", "attain", "earn", "collect"],
        "act": ["behave", "perform", "operate", "function", "do", "execute", "conduct"],
        "active": ["busy", "energetic", "lively", "dynamic", "vigorous", "engaged", "industrious"],
        "activity": ["action", "movement", "motion", "pursuit", "endeavor", "occupation", "exercise", "bustle"],
        "actual": ["real", "genuine", "true", "authentic", "factual", "concrete", "verified"],
        "adapt": ["adjust", "modify", "accommodate", "conform", "tailor", "acclimate", "evolve"],
        "add": ["include", "append", "attach", "supplement", "combine", "insert", "incorporate"],
        "adequate": ["sufficient", "enough", "satisfactory", "acceptable", "suitable", "decent", "passable"],
        "adjust": ["modify", "alter", "adapt", "change", "regulate", "fine-tune", "calibrate", "tweak"],
        "admire": ["respect", "esteem", "appreciate", "regard", "revere", "value", "look up to"],
        "admit": ["acknowledge", "confess", "concede", "accept", "recognize", "grant", "own up"],
        "adopt": ["embrace", "accept", "take on", "assume", "follow", "choose", "endorse"],
        "advance": ["progress", "proceed", "move forward", "improve", "promote", "develop", "further"],
        "advantage": ["benefit", "edge", "asset", "gain", "merit", "plus", "perk", "upper hand"],
        "afraid": ["scared", "frightened", "fearful", "terrified", "anxious", "alarmed", "nervous", "apprehensive"],
        "aggressive": ["hostile", "combative", "belligerent", "forceful", "assertive", "fierce", "pushy"],
        "agile": ["nimble", "quick", "lithe", "flexible", "deft", "sprightly", "limber"],
        "agree": ["concur", "consent", "accept", "approve", "comply", "assent", "correspond", "align"],
        "aid": ["help", "assist", "support", "facilitate", "serve", "contribute", "back"],
        "aim": ["goal", "objective", "target", "purpose", "intention", "ambition", "aspiration"],
        "alert": ["vigilant", "watchful", "attentive", "aware", "wary", "sharp", "observant"],
        "alive": ["living", "animate", "existing", "active", "vibrant", "thriving", "lively"],
        "allow": ["permit", "let", "authorize", "enable", "grant", "tolerate", "approve"],
        "alter": ["change", "modify", "adjust", "revise", "amend", "transform", "vary", "tweak"],
        "amaze": ["astonish", "astound", "stun", "surprise", "dazzle", "impress", "awe"],
        "amazing": ["astonishing", "incredible", "remarkable", "wonderful", "extraordinary", "stunning", "impressive"],
        "ambiguous": ["unclear", "vague", "equivocal", "uncertain", "doubtful", "cryptic", "nebulous"],
        "ample": ["plenty", "sufficient", "abundant", "generous", "copious", "spacious", "bountiful"],
        "analyze": ["examine", "study", "investigate", "evaluate", "assess", "inspect", "dissect", "review"],
        "ancient": ["old", "antique", "archaic", "historic", "aged", "bygone", "primeval"],
        "anger": ["fury", "rage", "wrath", "irritation", "indignation", "resentment", "hostility"],
        "angry": ["furious", "enraged", "irate", "livid", "outraged", "annoyed", "irritated", "mad"],
        "announce": ["declare", "proclaim", "reveal", "disclose", "state", "broadcast", "report"],
        "annoy": ["irritate", "bother", "pester", "vex", "aggravate", "bug", "hassle", "irk"],
        "answer": ["reply", "response", "retort", "solution", "explanation", "reaction", "comeback"],
        "anxious": ["worried", "nervous", "uneasy", "apprehensive", "concerned", "restless", "tense", "edgy"],
        "apparent": ["obvious", "evident", "clear", "visible", "plain", "noticeable", "manifest"],
        "appeal": ["attract", "interest", "fascinate", "charm", "please", "allure", "entice"],
        "appear": ["seem", "look", "emerge", "surface", "materialize", "arise", "show up"],
        "appropriate": ["suitable", "proper", "fitting", "apt", "relevant", "right", "correct"],
        "approve": ["endorse", "support", "sanction", "accept", "authorize", "ratify", "favor"],
        "area": ["region", "zone", "district", "territory", "sector", "domain", "field", "vicinity"],
        "argue": ["debate", "dispute", "contend", "quarrel", "bicker", "disagree", "clash"],
        "arrange": ["organize", "plan", "set up", "prepare", "sort", "order", "coordinate"],
        "arrive": ["come", "reach", "appear", "show up", "land", "turn up", "get there"],
        "arrogant": ["conceited", "haughty", "pompous", "smug", "self-important", "cocky", "egotistical"],
        "ask": ["inquire", "question", "query", "request", "demand", "seek", "probe"],
        "assemble": ["gather", "collect", "compile", "convene", "congregate", "build", "construct"],
        "assert": ["declare", "state", "claim", "maintain", "insist", "affirm", "contend"],
        "assign": ["allocate", "designate", "appoint", "delegate", "give", "distribute", "allot"],
        "assist": ["help", "aid", "support", "facilitate", "back", "serve", "contribute"],
        "assume": ["presume", "suppose", "expect", "guess", "believe", "reckon", "imagine"],
        "assure": ["guarantee", "promise", "ensure", "confirm", "reassure", "pledge", "certify"],
        "attach": ["connect", "fasten", "join", "link", "bind", "affix", "secure", "tie"],
        "attack": ["assault", "strike", "charge", "raid", "ambush", "offensive", "onslaught"],
        "attempt": ["try", "endeavor", "strive", "effort", "venture", "undertake", "seek"],
        "attract": ["draw", "lure", "entice", "appeal", "captivate", "charm", "allure", "tempt"],
        "attractive": ["appealing", "charming", "alluring", "handsome", "gorgeous", "lovely", "good-looking"],
        "avoid": ["evade", "dodge", "shun", "escape", "sidestep", "steer clear", "elude", "bypass"],
        "aware": ["conscious", "mindful", "informed", "alert", "cognizant", "attentive", "knowledgeable"],
        "awful": ["terrible", "dreadful", "horrible", "atrocious", "appalling", "ghastly", "horrendous"],
        "awkward": ["clumsy", "ungainly", "uncomfortable", "embarrassing", "uneasy", "ungraceful", "inept"],

        // B
        "bad": ["poor", "terrible", "awful", "dreadful", "inferior", "lousy", "unpleasant", "deficient"],
        "ban": ["prohibit", "forbid", "bar", "outlaw", "restrict", "block", "exclude", "veto"],
        "bare": ["naked", "exposed", "empty", "plain", "stark", "stripped", "barren"],
        "barrier": ["obstacle", "hurdle", "obstruction", "impediment", "hindrance", "blockade", "wall"],
        "basic": ["fundamental", "essential", "elementary", "primary", "core", "simple", "rudimentary"],
        "beautiful": ["gorgeous", "stunning", "lovely", "attractive", "elegant", "exquisite", "pretty", "handsome"],
        "become": ["turn", "grow", "develop", "evolve", "transform", "emerge", "change"],
        "begin": ["start", "commence", "initiate", "launch", "open", "embark", "originate", "kick off"],
        "behavior": ["conduct", "manner", "demeanor", "actions", "attitude", "deportment", "bearing"],
        "believe": ["trust", "accept", "think", "consider", "suppose", "assume", "reckon", "feel"],
        "beneficial": ["helpful", "useful", "advantageous", "favorable", "valuable", "rewarding", "productive"],
        "big": ["large", "huge", "enormous", "massive", "immense", "vast", "gigantic", "substantial"],
        "blame": ["accuse", "fault", "criticize", "condemn", "reproach", "censure", "hold responsible"],
        "bland": ["dull", "boring", "tasteless", "insipid", "flat", "uninteresting", "plain"],
        "bliss": ["joy", "happiness", "ecstasy", "delight", "euphoria", "rapture", "elation"],
        "block": ["obstruct", "hinder", "prevent", "impede", "bar", "halt", "stop", "deter"],
        "bold": ["brave", "daring", "courageous", "fearless", "audacious", "confident", "gutsy"],
        "boring": ["dull", "tedious", "monotonous", "uninteresting", "tiresome", "dreary", "humdrum"],
        "bother": ["annoy", "disturb", "irritate", "pester", "hassle", "trouble", "bug"],
        "brave": ["courageous", "fearless", "bold", "valiant", "heroic", "daring", "gallant", "intrepid"],
        "break": ["shatter", "crack", "fracture", "smash", "destroy", "rupture", "split", "snap"],
        "brief": ["short", "concise", "succinct", "quick", "fleeting", "momentary", "compact"],
        "bright": ["brilliant", "radiant", "vivid", "dazzling", "gleaming", "shining", "luminous", "smart"],
        "broad": ["wide", "extensive", "expansive", "vast", "sweeping", "comprehensive", "general"],
        "brutal": ["cruel", "savage", "vicious", "ruthless", "harsh", "merciless", "ferocious"],
        "build": ["construct", "create", "assemble", "erect", "establish", "develop", "make", "produce"],
        "busy": ["occupied", "engaged", "active", "hectic", "industrious", "swamped", "bustling"],

        // C
        "calm": ["peaceful", "serene", "tranquil", "placid", "composed", "relaxed", "still", "quiet"],
        "cancel": ["abort", "revoke", "annul", "void", "scrap", "call off", "rescind"],
        "capable": ["able", "competent", "skilled", "proficient", "qualified", "adept", "talented"],
        "capture": ["seize", "catch", "grab", "take", "trap", "snare", "apprehend", "nab"],
        "careful": ["cautious", "prudent", "attentive", "meticulous", "thorough", "wary", "vigilant"],
        "careless": ["reckless", "negligent", "sloppy", "thoughtless", "heedless", "lax", "irresponsible"],
        "cause": ["reason", "source", "origin", "trigger", "motive", "basis", "root", "grounds"],
        "caution": ["care", "prudence", "wariness", "vigilance", "discretion", "heed"],
        "cease": ["stop", "end", "halt", "quit", "discontinue", "conclude", "terminate", "desist"],
        "celebrate": ["commemorate", "honor", "observe", "rejoice", "mark", "toast", "praise"],
        "certain": ["sure", "confident", "definite", "positive", "convinced", "assured", "undoubted"],
        "challenge": ["dare", "contest", "test", "defy", "confront", "dispute", "provoke"],
        "change": ["alter", "modify", "transform", "adjust", "revise", "shift", "vary", "convert"],
        "charming": ["delightful", "enchanting", "captivating", "appealing", "attractive", "engaging", "lovely"],
        "cheap": ["inexpensive", "affordable", "economical", "budget", "bargain", "low-cost", "reasonable"],
        "cheat": ["deceive", "swindle", "trick", "defraud", "con", "dupe", "mislead"],
        "choose": ["select", "pick", "decide", "opt", "prefer", "elect", "settle on"],
        "clean": ["spotless", "immaculate", "pristine", "tidy", "neat", "pure", "sanitary"],
        "clear": ["obvious", "apparent", "evident", "transparent", "plain", "distinct", "visible"],
        "clever": ["smart", "intelligent", "brilliant", "shrewd", "ingenious", "sharp", "witty", "resourceful"],
        "close": ["near", "nearby", "adjacent", "shut", "conclude", "finish", "end", "seal"],
        "cold": ["chilly", "frigid", "freezing", "icy", "cool", "frosty", "wintry", "bitter"],
        "collect": ["gather", "accumulate", "assemble", "compile", "amass", "stockpile", "harvest"],
        "combine": ["merge", "blend", "unite", "mix", "fuse", "integrate", "join", "consolidate"],
        "come": ["arrive", "approach", "reach", "appear", "advance", "emerge", "show up"],
        "comfort": ["ease", "relief", "solace", "consolation", "reassurance", "soothe", "support"],
        "command": ["order", "direct", "instruct", "demand", "decree", "dictate", "mandate"],
        "common": ["usual", "ordinary", "typical", "frequent", "widespread", "prevalent", "familiar"],
        "communicate": ["convey", "express", "transmit", "relay", "share", "impart", "disclose"],
        "company": ["firm", "business", "corporation", "enterprise", "organization", "group"],
        "compare": ["contrast", "relate", "equate", "match", "parallel", "liken", "measure"],
        "compel": ["force", "oblige", "coerce", "require", "pressure", "drive", "make", "impel"],
        "compete": ["contend", "rival", "vie", "contest", "challenge", "battle", "strive"],
        "complain": ["grumble", "protest", "gripe", "whine", "object", "moan", "lament"],
        "complete": ["finish", "conclude", "accomplish", "fulfill", "finalize", "achieve", "wrap up"],
        "complex": ["complicated", "intricate", "elaborate", "involved", "sophisticated", "convoluted"],
        "comply": ["obey", "conform", "follow", "adhere", "observe", "submit", "respect"],
        "comprehend": ["understand", "grasp", "fathom", "perceive", "appreciate", "get", "follow"],
        "conceal": ["hide", "cover", "mask", "disguise", "cloak", "bury", "obscure", "veil"],
        "concentrate": ["focus", "center", "fixate", "channel", "direct", "intensify", "converge"],
        "concern": ["worry", "anxiety", "care", "interest", "matter", "issue", "regard"],
        "conclude": ["finish", "end", "close", "complete", "determine", "deduce", "wrap up"],
        "confident": ["assured", "self-assured", "certain", "poised", "bold", "secure", "positive"],
        "confirm": ["verify", "validate", "corroborate", "affirm", "certify", "substantiate", "prove"],
        "conflict": ["dispute", "clash", "struggle", "disagreement", "friction", "tension", "strife"],
        "confuse": ["bewilder", "puzzle", "perplex", "baffle", "muddle", "disorient", "mystify"],
        "connect": ["link", "join", "attach", "unite", "couple", "tie", "associate", "bridge"],
        "conscious": ["aware", "mindful", "alert", "awake", "cognizant", "attentive", "deliberate"],
        "consider": ["contemplate", "ponder", "deliberate", "reflect", "evaluate", "examine", "weigh", "think"],
        "consistent": ["steady", "constant", "uniform", "stable", "reliable", "dependable", "regular"],
        "constant": ["continuous", "persistent", "steady", "perpetual", "unchanging", "unceasing"],
        "construct": ["build", "create", "assemble", "erect", "make", "form", "fabricate"],
        "consume": ["eat", "devour", "use", "deplete", "exhaust", "spend", "absorb"],
        "contain": ["hold", "include", "encompass", "comprise", "house", "accommodate", "enclose"],
        "content": ["satisfied", "pleased", "happy", "fulfilled", "gratified", "comfortable", "at ease"],
        "continue": ["proceed", "persist", "resume", "maintain", "carry on", "sustain", "endure"],
        "contribute": ["give", "donate", "provide", "supply", "add", "offer", "lend"],
        "control": ["manage", "direct", "regulate", "govern", "command", "supervise", "oversee"],
        "convenient": ["handy", "practical", "accessible", "suitable", "useful", "nearby", "easy"],
        "convince": ["persuade", "sway", "influence", "win over", "assure", "convert"],
        "cool": ["chilly", "cold", "calm", "composed", "collected", "trendy", "stylish"],
        "correct": ["right", "accurate", "precise", "exact", "proper", "true", "valid", "appropriate"],
        "costly": ["expensive", "pricey", "dear", "steep", "premium", "lavish", "extravagant"],
        "courage": ["bravery", "valor", "nerve", "guts", "boldness", "daring", "fortitude", "mettle"],
        "courteous": ["polite", "respectful", "civil", "gracious", "mannerly", "considerate", "well-mannered"],
        "create": ["make", "produce", "generate", "design", "invent", "develop", "build", "craft"],
        "crisis": ["emergency", "disaster", "catastrophe", "calamity", "predicament", "plight"],
        "critical": ["crucial", "vital", "essential", "important", "key", "pivotal", "decisive"],
        "criticize": ["blame", "censure", "condemn", "fault", "denounce", "reproach", "pan"],
        "cruel": ["harsh", "brutal", "ruthless", "merciless", "heartless", "savage", "vicious", "mean"],
        "curious": ["inquisitive", "interested", "nosy", "intrigued", "questioning", "eager", "prying"],
        "current": ["present", "existing", "ongoing", "contemporary", "modern", "prevailing", "latest"],
        "cut": ["slice", "trim", "chop", "sever", "clip", "reduce", "carve", "slash"],

        // D
        "damage": ["harm", "hurt", "impair", "ruin", "wreck", "mar", "destroy", "injure"],
        "danger": ["risk", "hazard", "threat", "peril", "jeopardy", "menace"],
        "dangerous": ["hazardous", "risky", "perilous", "unsafe", "treacherous", "threatening", "harmful"],
        "dare": ["challenge", "risk", "venture", "brave", "attempt", "defy"],
        "dark": ["dim", "gloomy", "murky", "shadowy", "dusky", "obscure", "somber", "unlit"],
        "debate": ["discuss", "argue", "dispute", "deliberate", "contest", "contend"],
        "deceive": ["trick", "mislead", "fool", "cheat", "dupe", "delude", "swindle", "con"],
        "decide": ["determine", "choose", "resolve", "settle", "conclude", "judge", "opt"],
        "decline": ["decrease", "drop", "fall", "diminish", "shrink", "dwindle", "refuse", "reject"],
        "decrease": ["reduce", "diminish", "decline", "lessen", "shrink", "drop", "lower", "dwindle"],
        "dedicate": ["devote", "commit", "pledge", "assign", "allocate", "consecrate"],
        "deep": ["profound", "intense", "thorough", "bottomless", "vast", "far-reaching"],
        "defeat": ["beat", "overcome", "conquer", "vanquish", "overpower", "crush", "rout"],
        "defend": ["protect", "guard", "shield", "safeguard", "secure", "uphold", "support"],
        "definite": ["certain", "clear", "specific", "precise", "explicit", "unambiguous", "fixed"],
        "delay": ["postpone", "defer", "stall", "hold up", "put off", "procrastinate", "hinder"],
        "deliberate": ["intentional", "planned", "calculated", "purposeful", "conscious", "willful"],
        "delicate": ["fragile", "dainty", "subtle", "fine", "sensitive", "tender", "intricate"],
        "deliver": ["bring", "carry", "transport", "hand over", "supply", "distribute", "convey"],
        "demand": ["require", "request", "insist", "claim", "command", "order", "call for"],
        "demonstrate": ["show", "prove", "display", "illustrate", "exhibit", "manifest", "reveal"],
        "deny": ["refuse", "reject", "decline", "dispute", "contradict", "disallow", "rebuff"],
        "depart": ["leave", "go", "exit", "withdraw", "set off", "head out", "move on"],
        "depend": ["rely", "count on", "trust", "lean on", "hinge on", "rest on"],
        "depict": ["portray", "illustrate", "represent", "describe", "show", "render", "picture"],
        "deploy": ["station", "position", "arrange", "distribute", "utilize", "place", "employ"],
        "deprive": ["strip", "deny", "rob", "dispossess", "withhold", "starve", "divest"],
        "derive": ["obtain", "draw", "extract", "get", "gain", "deduce", "infer"],
        "describe": ["explain", "depict", "illustrate", "portray", "characterize", "outline", "detail"],
        "desire": ["want", "wish", "crave", "yearn", "long for", "covet", "hunger", "aspire"],
        "desperate": ["hopeless", "frantic", "dire", "urgent", "critical", "extreme", "reckless"],
        "destroy": ["demolish", "ruin", "wreck", "devastate", "annihilate", "obliterate", "shatter"],
        "detail": ["particular", "specifics", "element", "feature", "aspect", "point", "item"],
        "detect": ["discover", "find", "spot", "notice", "identify", "sense", "uncover"],
        "determine": ["decide", "establish", "ascertain", "resolve", "settle", "figure out", "conclude"],
        "develop": ["grow", "evolve", "advance", "progress", "expand", "mature", "improve", "build"],
        "devote": ["dedicate", "commit", "pledge", "give", "allocate", "assign", "apply"],
        "different": ["distinct", "diverse", "varied", "unique", "unlike", "separate", "dissimilar", "various"],
        "difficult": ["hard", "challenging", "tough", "demanding", "arduous", "complex", "strenuous"],
        "diminish": ["reduce", "decrease", "lessen", "shrink", "dwindle", "wane", "fade", "decline"],
        "direct": ["guide", "lead", "steer", "manage", "oversee", "conduct", "instruct", "aim"],
        "dirty": ["filthy", "grimy", "unclean", "soiled", "messy", "grubby", "stained", "polluted"],
        "disappear": ["vanish", "fade", "dissolve", "evaporate", "recede", "go away"],
        "discover": ["find", "uncover", "detect", "locate", "reveal", "spot", "identify", "stumble on"],
        "discuss": ["debate", "talk about", "examine", "consider", "review", "deliberate", "confer"],
        "disgusting": ["revolting", "repulsive", "nauseating", "sickening", "vile", "gross", "loathsome"],
        "display": ["show", "exhibit", "present", "demonstrate", "reveal", "showcase", "expose"],
        "distinct": ["different", "separate", "unique", "clear", "definite", "individual", "discrete"],
        "distribute": ["allocate", "dispense", "deliver", "spread", "divide", "hand out", "circulate"],
        "disturb": ["bother", "disrupt", "upset", "unsettle", "agitate", "trouble", "perturb"],
        "diverse": ["varied", "different", "assorted", "mixed", "various", "eclectic", "wide-ranging"],
        "divide": ["split", "separate", "partition", "segregate", "share", "distribute", "sever"],
        "doubt": ["question", "suspect", "distrust", "uncertainty", "skepticism", "hesitation"],
        "dramatic": ["striking", "vivid", "spectacular", "impressive", "theatrical", "bold", "intense"],
        "draw": ["sketch", "illustrate", "pull", "drag", "attract", "lure", "depict"],
        "dreadful": ["terrible", "awful", "horrible", "frightful", "appalling", "atrocious", "ghastly"],
        "dull": ["boring", "tedious", "bland", "uninteresting", "dreary", "monotonous", "dim"],
        "durable": ["lasting", "sturdy", "tough", "resilient", "robust", "enduring", "strong"],
        "duty": ["responsibility", "obligation", "task", "role", "job", "function", "charge"],

        // E
        "eager": ["keen", "enthusiastic", "anxious", "impatient", "avid", "excited", "willing"],
        "early": ["premature", "initial", "first", "advance", "prompt", "untimely"],
        "earn": ["make", "gain", "receive", "collect", "acquire", "obtain", "merit", "deserve"],
        "ease": ["comfort", "relief", "simplicity", "convenience", "effortlessness", "relaxation"],
        "easy": ["simple", "effortless", "straightforward", "uncomplicated", "painless", "manageable"],
        "eat": ["consume", "devour", "dine", "feast", "munch", "nibble", "chew", "ingest"],
        "edge": ["border", "rim", "brink", "margin", "verge", "boundary", "fringe", "advantage"],
        "educate": ["teach", "instruct", "train", "inform", "enlighten", "school", "tutor"],
        "effective": ["efficient", "productive", "successful", "potent", "powerful", "useful", "capable"],
        "efficient": ["effective", "productive", "organized", "streamlined", "competent", "capable"],
        "effort": ["attempt", "endeavor", "exertion", "struggle", "work", "labor", "try"],
        "elaborate": ["detailed", "complex", "intricate", "extensive", "thorough", "ornate", "fancy"],
        "elegant": ["graceful", "refined", "sophisticated", "stylish", "classy", "chic", "tasteful"],
        "eliminate": ["remove", "eradicate", "abolish", "discard", "erase", "exclude", "wipe out"],
        "embarrass": ["humiliate", "shame", "mortify", "disgrace", "fluster", "abash"],
        "embrace": ["hug", "accept", "adopt", "welcome", "hold", "enfold", "incorporate"],
        "emerge": ["appear", "surface", "arise", "come out", "materialize", "develop", "unfold"],
        "emotion": ["feeling", "sentiment", "passion", "sensation", "mood", "reaction", "affect"],
        "emphasize": ["stress", "highlight", "underline", "accentuate", "underscore", "focus on"],
        "employ": ["hire", "use", "utilize", "engage", "recruit", "apply", "deploy"],
        "empty": ["vacant", "hollow", "bare", "void", "blank", "deserted", "barren", "unoccupied"],
        "enable": ["allow", "permit", "empower", "facilitate", "authorize", "equip", "help"],
        "encounter": ["meet", "face", "confront", "experience", "come across", "run into"],
        "encourage": ["motivate", "inspire", "support", "urge", "promote", "boost", "cheer", "spur"],
        "end": ["finish", "conclude", "terminate", "cease", "close", "stop", "complete", "halt"],
        "endure": ["bear", "tolerate", "withstand", "survive", "sustain", "weather", "undergo"],
        "enemy": ["foe", "adversary", "opponent", "rival", "antagonist", "nemesis"],
        "energetic": ["active", "lively", "dynamic", "vigorous", "spirited", "animated", "vibrant"],
        "engage": ["involve", "participate", "occupy", "attract", "employ", "commit", "absorb"],
        "enjoy": ["relish", "savor", "appreciate", "delight in", "like", "love", "cherish"],
        "enormous": ["huge", "massive", "immense", "colossal", "gigantic", "vast", "tremendous"],
        "enough": ["sufficient", "adequate", "ample", "plenty", "satisfactory"],
        "ensure": ["guarantee", "secure", "assure", "confirm", "certify", "verify", "safeguard"],
        "enter": ["go in", "access", "join", "penetrate", "arrive", "come in"],
        "enthusiastic": ["eager", "passionate", "excited", "keen", "fervent", "zealous", "avid"],
        "entire": ["whole", "complete", "full", "total", "absolute", "utter", "thorough"],
        "error": ["mistake", "blunder", "fault", "slip", "flaw", "oversight", "gaffe", "inaccuracy"],
        "escape": ["flee", "evade", "avoid", "dodge", "elude", "getaway", "break free"],
        "essential": ["necessary", "vital", "crucial", "fundamental", "important", "critical", "key"],
        "establish": ["create", "found", "set up", "institute", "build", "form", "launch"],
        "estimate": ["approximate", "assess", "gauge", "calculate", "evaluate", "reckon", "guess"],
        "evaluate": ["assess", "judge", "appraise", "analyze", "review", "examine", "rate"],
        "even": ["level", "flat", "smooth", "uniform", "balanced", "equal", "steady"],
        "evident": ["obvious", "apparent", "clear", "plain", "visible", "manifest", "noticeable"],
        "evil": ["wicked", "malicious", "sinister", "vile", "corrupt", "immoral", "malevolent"],
        "exact": ["precise", "accurate", "specific", "correct", "perfect", "strict", "meticulous"],
        "exaggerate": ["overstate", "inflate", "embellish", "amplify", "magnify", "dramatize"],
        "examine": ["inspect", "study", "analyze", "review", "investigate", "scrutinize", "check"],
        "example": ["instance", "sample", "illustration", "case", "model", "specimen", "demonstration"],
        "excellent": ["outstanding", "superb", "exceptional", "magnificent", "splendid", "brilliant", "first-rate"],
        "excessive": ["extreme", "exorbitant", "unreasonable", "immoderate", "extravagant", "undue"],
        "exchange": ["swap", "trade", "switch", "substitute", "replace", "barter", "interchange"],
        "excited": ["thrilled", "eager", "enthusiastic", "elated", "animated", "exhilarated", "delighted"],
        "exclude": ["omit", "bar", "ban", "reject", "eliminate", "shut out", "leave out"],
        "execute": ["perform", "carry out", "implement", "accomplish", "complete", "fulfill", "do"],
        "exhibit": ["display", "show", "present", "demonstrate", "showcase", "reveal", "expose"],
        "exist": ["live", "be", "survive", "endure", "persist", "remain", "occur"],
        "expand": ["grow", "extend", "enlarge", "broaden", "widen", "increase", "develop", "spread"],
        "expect": ["anticipate", "await", "foresee", "predict", "assume", "count on", "look for"],
        "expensive": ["costly", "pricey", "dear", "steep", "premium", "extravagant", "overpriced"],
        "experience": ["encounter", "undergo", "feel", "endure", "face", "knowledge", "expertise"],
        "explain": ["clarify", "describe", "elaborate", "illustrate", "interpret", "define", "elucidate"],
        "explicit": ["clear", "direct", "specific", "definite", "precise", "unambiguous", "plain"],
        "explore": ["investigate", "examine", "study", "research", "probe", "survey", "scout"],
        "expose": ["reveal", "uncover", "disclose", "show", "unmask", "display", "bare"],
        "extend": ["expand", "stretch", "prolong", "lengthen", "widen", "broaden", "continue"],
        "extensive": ["wide", "broad", "comprehensive", "vast", "thorough", "sweeping", "far-reaching"],
        "extreme": ["severe", "intense", "drastic", "radical", "excessive", "ultimate", "utmost"],

        // F
        "fabricate": ["manufacture", "construct", "invent", "concoct", "forge", "create", "make up"],
        "face": ["confront", "encounter", "meet", "address", "tackle", "deal with", "brave"],
        "fact": ["truth", "reality", "certainty", "detail", "particular", "datum", "evidence"],
        "fail": ["flop", "falter", "collapse", "misfire", "bomb", "fall short", "miss"],
        "faint": ["dim", "weak", "pale", "feeble", "vague", "slight", "indistinct"],
        "fair": ["just", "equitable", "impartial", "reasonable", "unbiased", "honest", "balanced"],
        "faith": ["trust", "belief", "confidence", "conviction", "devotion", "loyalty", "reliance"],
        "fake": ["false", "counterfeit", "phony", "bogus", "forged", "artificial", "sham", "fraudulent"],
        "fall": ["drop", "descend", "plunge", "tumble", "decline", "collapse", "sink", "topple"],
        "familiar": ["known", "recognized", "common", "customary", "accustomed", "acquainted", "routine"],
        "famous": ["renowned", "celebrated", "notable", "prominent", "distinguished", "eminent", "well-known"],
        "fancy": ["elaborate", "ornate", "decorative", "luxurious", "extravagant", "lavish", "posh"],
        "fantastic": ["wonderful", "amazing", "incredible", "marvelous", "terrific", "superb", "excellent"],
        "far": ["distant", "remote", "faraway", "removed", "outlying", "extended"],
        "fascinate": ["captivate", "enchant", "intrigue", "mesmerize", "enthrall", "charm", "bewitch"],
        "fast": ["quick", "rapid", "swift", "speedy", "hasty", "brisk", "prompt", "nimble"],
        "fat": ["overweight", "plump", "chubby", "stout", "heavy", "portly", "obese", "thick"],
        "fatal": ["deadly", "lethal", "mortal", "terminal", "killing", "destructive"],
        "fault": ["defect", "flaw", "error", "mistake", "weakness", "shortcoming", "blame"],
        "favor": ["prefer", "support", "endorse", "approve", "like", "lean toward", "back"],
        "fear": ["dread", "terror", "fright", "anxiety", "alarm", "panic", "apprehension", "worry"],
        "feature": ["characteristic", "trait", "attribute", "quality", "aspect", "property", "element"],
        "feeble": ["weak", "frail", "fragile", "puny", "flimsy", "infirm", "delicate"],
        "feel": ["sense", "perceive", "experience", "detect", "notice", "touch", "believe"],
        "ferocious": ["fierce", "savage", "brutal", "vicious", "wild", "intense", "violent"],
        "fertile": ["productive", "fruitful", "rich", "lush", "abundant", "prolific", "bountiful"],
        "fierce": ["ferocious", "intense", "savage", "violent", "aggressive", "brutal", "wild"],
        "fight": ["battle", "combat", "struggle", "conflict", "clash", "contest", "brawl", "quarrel"],
        "figure": ["calculate", "compute", "determine", "shape", "form", "silhouette", "number"],
        "fill": ["load", "pack", "stuff", "occupy", "complete", "stock", "top up"],
        "final": ["last", "ultimate", "concluding", "terminal", "closing", "definitive", "decisive"],
        "find": ["discover", "locate", "detect", "uncover", "identify", "spot", "encounter", "notice"],
        "fine": ["good", "excellent", "delicate", "thin", "narrow", "subtle", "refined", "superior"],
        "finish": ["complete", "end", "conclude", "wrap up", "accomplish", "finalize", "close"],
        "firm": ["solid", "hard", "rigid", "stable", "steady", "resolute", "determined", "strong"],
        "fit": ["suitable", "appropriate", "proper", "healthy", "apt", "right", "qualified"],
        "fix": ["repair", "mend", "restore", "correct", "patch", "remedy", "resolve", "adjust"],
        "flexible": ["adaptable", "versatile", "pliable", "elastic", "adjustable", "supple", "limber"],
        "fly": ["soar", "glide", "hover", "float", "sail", "wing", "drift", "ascend"],
        "focus": ["concentrate", "center", "direct", "target", "aim", "fixate", "zero in"],
        "follow": ["pursue", "trail", "track", "chase", "succeed", "observe", "obey", "comply"],
        "foolish": ["silly", "stupid", "unwise", "absurd", "senseless", "idiotic", "reckless"],
        "forbid": ["prohibit", "ban", "bar", "disallow", "outlaw", "prevent", "block", "veto"],
        "force": ["compel", "coerce", "pressure", "make", "drive", "push", "oblige", "power"],
        "foreign": ["alien", "overseas", "exotic", "external", "strange", "unfamiliar", "imported"],
        "forever": ["always", "permanently", "eternally", "endlessly", "perpetually", "indefinitely"],
        "forget": ["neglect", "overlook", "disregard", "ignore", "omit", "lose track"],
        "forgive": ["pardon", "excuse", "absolve", "condone", "overlook", "let go"],
        "form": ["shape", "create", "build", "construct", "mold", "fashion", "develop", "make"],
        "formal": ["official", "proper", "conventional", "ceremonial", "traditional", "stiff"],
        "fortunate": ["lucky", "blessed", "favored", "privileged", "happy", "prosperous"],
        "found": ["establish", "create", "start", "set up", "institute", "launch", "build"],
        "fragile": ["delicate", "frail", "breakable", "brittle", "flimsy", "weak", "dainty"],
        "frank": ["candid", "honest", "direct", "blunt", "outspoken", "straightforward", "open"],
        "free": ["liberate", "release", "loose", "complimentary", "gratis", "independent", "unrestricted"],
        "frequent": ["common", "regular", "recurrent", "repeated", "habitual", "persistent", "usual"],
        "fresh": ["new", "recent", "original", "novel", "clean", "crisp", "unused", "pure"],
        "friend": ["companion", "ally", "pal", "buddy", "associate", "comrade", "confidant", "mate"],
        "frighten": ["scare", "terrify", "alarm", "startle", "intimidate", "shock", "spook"],
        "frustrate": ["thwart", "foil", "hinder", "impede", "block", "defeat", "discourage"],
        "full": ["complete", "entire", "whole", "packed", "filled", "loaded", "brimming", "total"],
        "fun": ["enjoyment", "pleasure", "amusement", "entertainment", "recreation", "delight"],
        "funny": ["humorous", "amusing", "comical", "hilarious", "witty", "entertaining", "laughable"],
        "furious": ["angry", "enraged", "livid", "irate", "outraged", "incensed", "infuriated", "mad"],
        "future": ["upcoming", "forthcoming", "coming", "prospect", "outlook", "tomorrow"],

        // G
        "gain": ["acquire", "obtain", "earn", "achieve", "win", "secure", "profit", "benefit"],
        "gather": ["collect", "assemble", "accumulate", "compile", "amass", "congregate", "convene"],
        "generous": ["giving", "charitable", "liberal", "unselfish", "benevolent", "magnanimous", "kind"],
        "gentle": ["mild", "soft", "tender", "kind", "calm", "soothing", "delicate", "subtle"],
        "genuine": ["authentic", "real", "true", "sincere", "legitimate", "original", "honest"],
        "get": ["obtain", "acquire", "receive", "gain", "fetch", "procure", "secure", "attain"],
        "give": ["provide", "offer", "donate", "present", "deliver", "supply", "grant", "bestow"],
        "glad": ["happy", "pleased", "delighted", "content", "cheerful", "joyful", "thrilled"],
        "go": ["move", "travel", "proceed", "advance", "depart", "leave", "journey", "head"],
        "good": ["fine", "great", "excellent", "superior", "wonderful", "decent", "favorable", "quality"],
        "gorgeous": ["beautiful", "stunning", "magnificent", "lovely", "splendid", "dazzling", "exquisite"],
        "govern": ["rule", "lead", "manage", "direct", "control", "administer", "regulate", "oversee"],
        "graceful": ["elegant", "refined", "fluid", "smooth", "poised", "agile", "nimble"],
        "gradual": ["slow", "progressive", "steady", "incremental", "moderate", "gentle", "step-by-step"],
        "grand": ["magnificent", "impressive", "majestic", "splendid", "stately", "glorious", "noble"],
        "grant": ["give", "award", "bestow", "provide", "confer", "allocate", "approve", "fund"],
        "grateful": ["thankful", "appreciative", "indebted", "obliged", "pleased", "beholden"],
        "grave": ["serious", "severe", "critical", "solemn", "grim", "somber", "dire"],
        "great": ["excellent", "magnificent", "superb", "outstanding", "remarkable", "fantastic", "wonderful"],
        "greedy": ["selfish", "avaricious", "grasping", "acquisitive", "materialistic", "insatiable"],
        "grieve": ["mourn", "lament", "sorrow", "weep", "suffer", "agonize", "ache"],
        "grim": ["stern", "bleak", "harsh", "forbidding", "somber", "dismal", "dire"],
        "grip": ["hold", "grasp", "clutch", "clasp", "seize", "clench", "grab"],
        "ground": ["basis", "foundation", "earth", "soil", "land", "terrain", "surface"],
        "group": ["team", "cluster", "collection", "assembly", "bunch", "set", "band", "gathering"],
        "grow": ["expand", "increase", "develop", "mature", "flourish", "thrive", "enlarge", "progress"],
        "guarantee": ["assure", "ensure", "promise", "pledge", "warrant", "certify", "vouch"],
        "guard": ["protect", "defend", "shield", "watch", "secure", "safeguard", "patrol"],
        "guess": ["estimate", "suppose", "speculate", "assume", "conjecture", "predict", "reckon"],
        "guide": ["lead", "direct", "steer", "advise", "mentor", "counsel", "navigate", "instruct"],

        // H
        "habit": ["routine", "custom", "practice", "pattern", "tendency", "tradition"],
        "halt": ["stop", "cease", "pause", "end", "freeze", "discontinue", "suspend"],
        "handle": ["manage", "deal with", "cope", "address", "tackle", "control", "process"],
        "happen": ["occur", "take place", "arise", "transpire", "unfold", "develop", "come about"],
        "happy": ["joyful", "cheerful", "delighted", "pleased", "content", "elated", "glad", "merry"],
        "hard": ["difficult", "tough", "challenging", "demanding", "strenuous", "arduous", "rigid", "firm"],
        "harm": ["damage", "hurt", "injure", "impair", "wound", "ruin", "endanger"],
        "harsh": ["severe", "rough", "strict", "stern", "brutal", "cruel", "grating", "unforgiving"],
        "haste": ["hurry", "rush", "speed", "urgency", "swiftness", "quickness"],
        "hate": ["despise", "loathe", "detest", "abhor", "dislike", "resent", "scorn"],
        "have": ["possess", "own", "hold", "contain", "include", "retain", "carry"],
        "heal": ["cure", "recover", "mend", "repair", "treat", "remedy", "restore"],
        "healthy": ["fit", "well", "robust", "strong", "sound", "wholesome", "vigorous"],
        "heavy": ["weighty", "hefty", "bulky", "dense", "ponderous", "massive", "substantial"],
        "help": ["assist", "aid", "support", "facilitate", "guide", "serve", "contribute", "boost"],
        "hesitate": ["pause", "waver", "falter", "stall", "delay", "dither", "vacillate"],
        "hide": ["conceal", "cover", "obscure", "mask", "camouflage", "shelter", "cloak", "stash"],
        "high": ["tall", "elevated", "lofty", "towering", "soaring", "raised", "steep"],
        "hinder": ["obstruct", "impede", "hamper", "block", "delay", "prevent", "thwart", "restrict"],
        "honest": ["truthful", "sincere", "genuine", "candid", "frank", "trustworthy", "upright"],
        "honor": ["respect", "esteem", "dignity", "integrity", "tribute", "praise", "glory"],
        "hope": ["wish", "desire", "aspiration", "expectation", "optimism", "dream", "ambition"],
        "horrible": ["terrible", "dreadful", "awful", "horrific", "ghastly", "appalling", "atrocious"],
        "hostile": ["unfriendly", "aggressive", "antagonistic", "belligerent", "combative", "adverse"],
        "hot": ["warm", "burning", "scorching", "boiling", "searing", "blazing", "sweltering", "fiery"],
        "huge": ["enormous", "massive", "immense", "colossal", "gigantic", "vast", "tremendous"],
        "humble": ["modest", "meek", "unassuming", "unpretentious", "simple", "lowly"],
        "hungry": ["famished", "starving", "ravenous", "peckish", "voracious", "craving"],
        "hurry": ["rush", "hasten", "hustle", "dash", "scurry", "speed", "race"],
        "hurt": ["injure", "harm", "wound", "damage", "ache", "pain", "sting", "bruise"],

        // I
        "idea": ["concept", "thought", "notion", "plan", "suggestion", "theory", "proposal", "vision"],
        "identify": ["recognize", "detect", "determine", "pinpoint", "distinguish", "name", "spot"],
        "ignore": ["disregard", "overlook", "neglect", "dismiss", "snub", "bypass", "skip"],
        "illustrate": ["demonstrate", "show", "depict", "explain", "clarify", "portray", "exemplify"],
        "imagine": ["envision", "picture", "conceive", "visualize", "fancy", "suppose", "dream"],
        "immediate": ["instant", "prompt", "urgent", "pressing", "direct", "swift", "sudden"],
        "immense": ["huge", "enormous", "vast", "massive", "colossal", "tremendous", "gigantic"],
        "impact": ["effect", "influence", "consequence", "impression", "result", "force", "significance"],
        "imply": ["suggest", "hint", "indicate", "insinuate", "mean", "signify", "intimate"],
        "important": ["significant", "crucial", "vital", "essential", "critical", "key", "major", "meaningful"],
        "impose": ["enforce", "apply", "inflict", "dictate", "force", "mandate", "levy"],
        "impress": ["amaze", "inspire", "dazzle", "awe", "move", "strike", "influence"],
        "impressive": ["striking", "remarkable", "stunning", "magnificent", "grand", "formidable"],
        "improve": ["enhance", "upgrade", "refine", "better", "boost", "advance", "develop", "polish"],
        "include": ["contain", "comprise", "encompass", "incorporate", "cover", "embrace", "involve"],
        "increase": ["grow", "expand", "rise", "escalate", "boost", "enlarge", "amplify", "multiply"],
        "indicate": ["show", "suggest", "signal", "point to", "imply", "reveal", "denote"],
        "influence": ["affect", "impact", "sway", "shape", "guide", "persuade", "motivate"],
        "inform": ["tell", "notify", "advise", "update", "brief", "alert", "enlighten"],
        "initial": ["first", "opening", "beginning", "original", "primary", "starting", "introductory"],
        "innocent": ["blameless", "guiltless", "pure", "naive", "harmless", "virtuous", "faultless"],
        "inquire": ["ask", "investigate", "probe", "query", "question", "examine", "explore"],
        "insist": ["demand", "assert", "maintain", "persist", "stress", "urge", "press"],
        "inspect": ["examine", "check", "review", "survey", "scrutinize", "study", "investigate"],
        "inspire": ["motivate", "encourage", "stimulate", "uplift", "move", "ignite", "spark"],
        "install": ["set up", "place", "put in", "position", "mount", "fit", "establish"],
        "instant": ["immediate", "prompt", "swift", "quick", "sudden", "rapid", "moment"],
        "intelligent": ["smart", "clever", "brilliant", "bright", "sharp", "gifted", "astute", "wise"],
        "intense": ["extreme", "severe", "fierce", "powerful", "strong", "passionate", "deep"],
        "interest": ["concern", "curiosity", "attention", "fascination", "involvement", "passion"],
        "interesting": ["fascinating", "engaging", "intriguing", "captivating", "compelling", "absorbing"],
        "interpret": ["explain", "translate", "decipher", "construe", "understand", "read", "analyze"],
        "introduce": ["present", "launch", "unveil", "propose", "initiate", "establish", "bring in"],
        "invade": ["attack", "occupy", "infiltrate", "overrun", "encroach", "trespass", "intrude"],
        "investigate": ["examine", "explore", "study", "probe", "research", "analyze", "inspect"],
        "involve": ["include", "engage", "entail", "require", "concern", "implicate", "encompass"],
        "irritate": ["annoy", "bother", "aggravate", "vex", "provoke", "exasperate", "pester"],
        "isolate": ["separate", "detach", "segregate", "seclude", "quarantine", "cut off"],

        // J-K
        "jealous": ["envious", "covetous", "resentful", "possessive", "suspicious", "begrudging"],
        "job": ["work", "occupation", "profession", "career", "position", "role", "employment"],
        "join": ["connect", "unite", "combine", "link", "merge", "attach", "associate", "participate"],
        "journey": ["trip", "voyage", "travel", "expedition", "trek", "tour", "passage"],
        "joy": ["happiness", "delight", "pleasure", "bliss", "elation", "glee", "euphoria", "cheer"],
        "judge": ["assess", "evaluate", "determine", "decide", "rate", "appraise", "consider"],
        "justify": ["defend", "explain", "validate", "support", "warrant", "rationalize", "vindicate"],
        "keen": ["eager", "enthusiastic", "sharp", "avid", "interested", "passionate", "acute"],
        "keep": ["retain", "hold", "maintain", "preserve", "store", "save", "guard", "protect"],
        "key": ["crucial", "essential", "vital", "important", "central", "critical", "fundamental"],
        "kill": ["slay", "eliminate", "destroy", "exterminate", "execute", "dispatch", "annihilate"],
        "kind": ["generous", "gentle", "caring", "compassionate", "considerate", "thoughtful", "benevolent"],
        "know": ["understand", "comprehend", "recognize", "realize", "perceive", "grasp", "be aware"],

        // L
        "lack": ["shortage", "deficiency", "absence", "scarcity", "want", "need", "deficit"],
        "large": ["big", "huge", "enormous", "massive", "vast", "immense", "substantial", "spacious"],
        "last": ["final", "ultimate", "concluding", "closing", "endmost", "latest", "terminal"],
        "late": ["overdue", "delayed", "tardy", "belated", "behind", "slow", "recent"],
        "laugh": ["chuckle", "giggle", "snicker", "cackle", "guffaw", "chortle", "howl"],
        "launch": ["start", "begin", "initiate", "introduce", "commence", "unveil", "kick off"],
        "lazy": ["idle", "indolent", "sluggish", "lethargic", "inactive", "slothful", "listless"],
        "lead": ["guide", "direct", "head", "conduct", "steer", "manage", "command", "govern"],
        "lean": ["thin", "slender", "slim", "spare", "skinny", "trim", "lanky"],
        "learn": ["study", "discover", "absorb", "master", "acquire", "grasp", "pick up"],
        "leave": ["depart", "go", "exit", "withdraw", "abandon", "vacate", "quit"],
        "legitimate": ["valid", "legal", "lawful", "genuine", "authentic", "proper", "rightful"],
        "lenient": ["tolerant", "mild", "easygoing", "forgiving", "permissive", "indulgent", "lax"],
        "liberal": ["generous", "open-minded", "progressive", "tolerant", "broad-minded", "permissive"],
        "light": ["bright", "luminous", "radiant", "pale", "lightweight", "faint", "airy"],
        "like": ["enjoy", "appreciate", "prefer", "admire", "favor", "fancy", "relish"],
        "limit": ["restrict", "confine", "cap", "restrain", "curb", "bound", "constrain"],
        "little": ["small", "tiny", "minute", "miniature", "petite", "slight", "compact", "modest"],
        "lively": ["energetic", "spirited", "vibrant", "animated", "dynamic", "vivacious", "active"],
        "logical": ["rational", "reasonable", "sensible", "coherent", "sound", "valid", "systematic"],
        "lonely": ["isolated", "alone", "solitary", "lonesome", "forlorn", "secluded", "desolate"],
        "long": ["extended", "lengthy", "prolonged", "extensive", "enduring", "sustained", "protracted"],
        "look": ["see", "glance", "gaze", "stare", "observe", "watch", "peer", "view"],
        "loose": ["slack", "relaxed", "baggy", "free", "unfastened", "detached", "wobbly"],
        "lose": ["misplace", "forfeit", "miss", "drop", "surrender", "sacrifice"],
        "loud": ["noisy", "boisterous", "deafening", "thunderous", "blaring", "roaring", "piercing"],
        "love": ["adore", "cherish", "treasure", "worship", "admire", "fancy", "care for"],
        "loyal": ["faithful", "devoted", "dedicated", "true", "steadfast", "reliable", "committed"],
        "lucky": ["fortunate", "blessed", "favored", "charmed", "providential", "auspicious"],

        // M
        "mad": ["angry", "furious", "crazy", "insane", "irate", "livid", "enraged", "deranged"],
        "magnificent": ["splendid", "grand", "glorious", "majestic", "superb", "stunning", "impressive"],
        "maintain": ["keep", "preserve", "sustain", "uphold", "continue", "retain", "support"],
        "major": ["significant", "important", "key", "principal", "chief", "primary", "leading"],
        "make": ["create", "build", "construct", "produce", "manufacture", "craft", "form", "generate"],
        "manage": ["handle", "direct", "control", "supervise", "run", "administer", "oversee"],
        "mandatory": ["required", "compulsory", "obligatory", "necessary", "essential", "binding"],
        "manipulate": ["control", "influence", "exploit", "maneuver", "handle", "rig", "steer"],
        "many": ["numerous", "several", "multiple", "countless", "various", "abundant", "plentiful"],
        "mark": ["sign", "symbol", "indicator", "stamp", "brand", "label", "trace"],
        "massive": ["huge", "enormous", "immense", "colossal", "vast", "gigantic", "monumental"],
        "matter": ["issue", "subject", "topic", "concern", "affair", "question", "substance"],
        "mature": ["grown", "adult", "ripe", "developed", "seasoned", "experienced", "wise"],
        "mean": ["cruel", "unkind", "nasty", "harsh", "spiteful", "malicious", "heartless", "average"],
        "measure": ["gauge", "assess", "evaluate", "calculate", "determine", "quantify", "weigh"],
        "mediocre": ["average", "ordinary", "so-so", "middling", "passable", "unremarkable", "fair"],
        "mention": ["refer to", "note", "cite", "state", "remark", "touch on", "bring up"],
        "mild": ["gentle", "moderate", "soft", "subtle", "temperate", "calm", "lenient"],
        "minor": ["small", "insignificant", "trivial", "slight", "petty", "secondary", "lesser"],
        "mistake": ["error", "blunder", "fault", "oversight", "slip", "lapse", "misstep", "gaffe"],
        "mix": ["blend", "combine", "merge", "mingle", "stir", "fuse", "integrate"],
        "moderate": ["reasonable", "mild", "temperate", "average", "modest", "fair", "balanced"],
        "modern": ["contemporary", "current", "recent", "new", "up-to-date", "present-day", "latest"],
        "modify": ["change", "alter", "adjust", "adapt", "revise", "amend", "tweak", "update"],
        "money": ["cash", "funds", "currency", "capital", "wealth", "finances", "revenue"],
        "monitor": ["watch", "observe", "track", "oversee", "check", "supervise", "survey"],
        "monopolize": ["dominate", "control", "corner", "hog", "command", "take over"],
        "monotonous": ["boring", "tedious", "dull", "repetitive", "humdrum", "tiresome", "dreary"],
        "mood": ["feeling", "temper", "disposition", "humor", "state of mind", "spirit", "attitude"],
        "moral": ["ethical", "virtuous", "righteous", "principled", "honorable", "decent", "just"],
        "move": ["shift", "transfer", "relocate", "transport", "advance", "proceed", "budge"],
        "mutual": ["shared", "common", "reciprocal", "joint", "collective", "two-way"],

        // N
        "naive": ["innocent", "gullible", "trusting", "unsophisticated", "inexperienced", "simple"],
        "narrow": ["thin", "slim", "slender", "tight", "restricted", "limited", "confined"],
        "natural": ["normal", "organic", "innate", "inherent", "genuine", "native", "instinctive"],
        "neat": ["tidy", "orderly", "organized", "clean", "trim", "immaculate", "smart"],
        "necessary": ["essential", "required", "needed", "vital", "crucial", "mandatory", "indispensable"],
        "need": ["require", "demand", "want", "necessitate", "desire", "crave", "lack"],
        "neglect": ["ignore", "overlook", "disregard", "abandon", "forsake", "omit", "skip"],
        "negotiate": ["bargain", "discuss", "mediate", "arrange", "broker", "settle", "confer"],
        "nervous": ["anxious", "uneasy", "tense", "edgy", "worried", "jittery", "apprehensive"],
        "neutral": ["impartial", "unbiased", "objective", "detached", "dispassionate", "fair"],
        "new": ["fresh", "novel", "recent", "modern", "latest", "original", "current", "innovative"],
        "nice": ["pleasant", "agreeable", "lovely", "delightful", "charming", "wonderful", "kind"],
        "noble": ["dignified", "honorable", "virtuous", "worthy", "grand", "majestic", "stately"],
        "noisy": ["loud", "boisterous", "rowdy", "clamorous", "deafening", "raucous", "thunderous"],
        "normal": ["usual", "ordinary", "typical", "standard", "regular", "common", "conventional"],
        "notable": ["remarkable", "noteworthy", "significant", "distinguished", "prominent", "outstanding"],
        "notice": ["observe", "see", "detect", "spot", "perceive", "note", "recognize"],
        "notify": ["inform", "tell", "alert", "advise", "announce", "warn", "update"],
        "nourish": ["feed", "nurture", "sustain", "support", "fortify", "strengthen"],

        // O
        "obey": ["comply", "follow", "observe", "submit", "conform", "respect", "abide by"],
        "object": ["protest", "oppose", "disagree", "challenge", "complain", "resist"],
        "objective": ["goal", "aim", "target", "purpose", "intention", "mission", "impartial"],
        "obligate": ["compel", "require", "bind", "force", "commit", "mandate"],
        "observe": ["watch", "notice", "see", "monitor", "witness", "study", "remark"],
        "obsolete": ["outdated", "antiquated", "archaic", "old-fashioned", "extinct", "defunct"],
        "obstacle": ["barrier", "hurdle", "impediment", "obstruction", "hindrance", "block"],
        "obtain": ["get", "acquire", "gain", "secure", "procure", "attain", "receive", "earn"],
        "obvious": ["clear", "evident", "apparent", "plain", "visible", "noticeable", "unmistakable"],
        "occur": ["happen", "take place", "arise", "transpire", "develop", "emerge", "unfold"],
        "odd": ["strange", "unusual", "peculiar", "weird", "bizarre", "curious", "eccentric", "quirky"],
        "offend": ["insult", "upset", "affront", "outrage", "hurt", "displease", "irritate"],
        "offer": ["provide", "present", "propose", "extend", "give", "suggest", "submit"],
        "old": ["ancient", "aged", "elderly", "vintage", "antique", "mature", "senior"],
        "omit": ["exclude", "skip", "leave out", "drop", "overlook", "neglect", "miss"],
        "open": ["unlock", "uncover", "reveal", "expose", "unfold", "accessible", "available"],
        "opinion": ["view", "belief", "perspective", "judgment", "stance", "position", "outlook"],
        "opponent": ["rival", "adversary", "competitor", "enemy", "foe", "challenger", "contender"],
        "opportunity": ["chance", "opening", "prospect", "occasion", "possibility", "break"],
        "oppose": ["resist", "challenge", "defy", "contest", "object to", "counter", "fight"],
        "optional": ["voluntary", "elective", "discretionary", "noncompulsory", "flexible"],
        "ordinary": ["normal", "usual", "common", "typical", "standard", "regular", "average"],
        "organize": ["arrange", "sort", "coordinate", "plan", "structure", "order", "systematize"],
        "origin": ["source", "beginning", "root", "cause", "foundation", "basis", "genesis"],
        "outstanding": ["excellent", "exceptional", "superb", "remarkable", "distinguished", "superior"],
        "overcome": ["conquer", "defeat", "surmount", "prevail", "triumph", "beat", "master"],
        "overlook": ["ignore", "miss", "neglect", "disregard", "skip", "omit", "forget"],

        // P
        "particular": ["specific", "certain", "precise", "exact", "individual", "distinct", "special"],
        "passion": ["enthusiasm", "fervor", "devotion", "zeal", "ardor", "intensity", "love"],
        "patience": ["tolerance", "endurance", "persistence", "composure", "restraint", "fortitude"],
        "peaceful": ["calm", "serene", "tranquil", "quiet", "harmonious", "placid", "restful"],
        "peculiar": ["strange", "odd", "unusual", "weird", "curious", "eccentric", "bizarre"],
        "perfect": ["flawless", "ideal", "excellent", "faultless", "impeccable", "pristine", "superb"],
        "perform": ["execute", "carry out", "do", "accomplish", "conduct", "fulfill", "act"],
        "permanent": ["lasting", "enduring", "fixed", "perpetual", "constant", "eternal", "stable"],
        "permit": ["allow", "authorize", "let", "approve", "enable", "grant", "consent"],
        "persist": ["continue", "endure", "persevere", "last", "remain", "insist", "carry on"],
        "persuade": ["convince", "sway", "influence", "urge", "coax", "win over", "talk into"],
        "plan": ["strategy", "scheme", "design", "blueprint", "agenda", "proposal", "arrangement"],
        "pleasant": ["nice", "agreeable", "enjoyable", "delightful", "charming", "lovely", "pleasing"],
        "plentiful": ["abundant", "ample", "copious", "profuse", "generous", "bountiful", "rich"],
        "polite": ["courteous", "respectful", "civil", "mannerly", "gracious", "refined", "considerate"],
        "poor": ["impoverished", "needy", "penniless", "broke", "disadvantaged", "destitute", "inferior"],
        "popular": ["well-liked", "famous", "widespread", "common", "trendy", "favored", "mainstream"],
        "possible": ["feasible", "viable", "achievable", "attainable", "plausible", "potential"],
        "postpone": ["delay", "defer", "put off", "shelve", "reschedule", "suspend", "table"],
        "potential": ["possible", "prospective", "likely", "promising", "capability", "capacity"],
        "power": ["strength", "force", "authority", "energy", "might", "influence", "control"],
        "powerful": ["strong", "mighty", "potent", "forceful", "dominant", "influential", "robust"],
        "practical": ["useful", "functional", "realistic", "sensible", "pragmatic", "handy", "workable"],
        "praise": ["commend", "applaud", "honor", "compliment", "acclaim", "celebrate", "admire"],
        "precise": ["exact", "accurate", "specific", "meticulous", "detailed", "strict", "rigorous"],
        "predict": ["forecast", "foresee", "anticipate", "project", "expect", "prophesy", "estimate"],
        "prefer": ["favor", "choose", "like", "opt for", "lean toward", "select", "desire"],
        "prepare": ["ready", "arrange", "organize", "plan", "set up", "equip", "gear up"],
        "preserve": ["protect", "maintain", "conserve", "keep", "safeguard", "save", "uphold"],
        "prevent": ["stop", "avoid", "block", "hinder", "deter", "inhibit", "avert", "thwart"],
        "primary": ["main", "principal", "chief", "first", "leading", "foremost", "central"],
        "private": ["personal", "confidential", "secret", "intimate", "individual", "exclusive"],
        "problem": ["issue", "difficulty", "challenge", "obstacle", "dilemma", "complication", "trouble"],
        "proceed": ["continue", "advance", "go ahead", "progress", "move on", "carry on"],
        "produce": ["create", "make", "generate", "manufacture", "yield", "develop", "craft"],
        "profit": ["gain", "benefit", "earnings", "income", "revenue", "return", "proceeds"],
        "prohibit": ["ban", "forbid", "bar", "outlaw", "restrict", "prevent", "disallow"],
        "prominent": ["notable", "distinguished", "eminent", "famous", "leading", "outstanding"],
        "promote": ["advance", "support", "encourage", "boost", "advocate", "endorse", "further"],
        "prompt": ["quick", "immediate", "swift", "timely", "punctual", "rapid", "instant"],
        "proper": ["correct", "appropriate", "suitable", "fitting", "right", "decent", "adequate"],
        "propose": ["suggest", "recommend", "offer", "submit", "present", "put forward"],
        "prosper": ["thrive", "flourish", "succeed", "boom", "grow", "advance", "blossom"],
        "protect": ["defend", "guard", "shield", "safeguard", "preserve", "secure", "shelter"],
        "proud": ["pleased", "satisfied", "fulfilled", "dignified", "arrogant", "conceited"],
        "prove": ["demonstrate", "verify", "confirm", "establish", "validate", "show", "substantiate"],
        "provide": ["supply", "offer", "give", "furnish", "deliver", "present", "contribute"],
        "provoke": ["irritate", "anger", "annoy", "agitate", "incite", "trigger", "stimulate"],
        "prudent": ["wise", "cautious", "careful", "sensible", "judicious", "shrewd", "discreet"],
        "pull": ["tug", "drag", "draw", "haul", "yank", "tow", "extract", "wrench"],
        "punish": ["penalize", "discipline", "sanction", "chastise", "fine", "sentence"],
        "purchase": ["buy", "acquire", "obtain", "procure", "invest in", "get", "pick up"],
        "pure": ["clean", "genuine", "untainted", "unadulterated", "pristine", "innocent", "absolute"],
        "purpose": ["goal", "aim", "objective", "intention", "reason", "mission", "function"],
        "pursue": ["follow", "chase", "seek", "track", "strive for", "go after", "hunt"],
        "push": ["shove", "press", "thrust", "force", "propel", "drive", "nudge"],
        "put": ["place", "set", "position", "lay", "deposit", "situate", "locate"],

        // Q
        "qualify": ["meet", "satisfy", "certify", "entitle", "equip", "prepare", "pass"],
        "quality": ["standard", "caliber", "grade", "excellence", "attribute", "characteristic"],
        "quarrel": ["argue", "fight", "dispute", "disagree", "bicker", "clash", "squabble"],
        "question": ["inquiry", "query", "issue", "doubt", "matter", "concern", "puzzle"],
        "quick": ["fast", "rapid", "swift", "speedy", "prompt", "brisk", "hasty", "nimble"],
        "quiet": ["silent", "still", "hushed", "peaceful", "calm", "muted", "tranquil", "serene"],
        "quit": ["stop", "leave", "resign", "abandon", "cease", "give up", "withdraw"],

        // R
        "raise": ["lift", "elevate", "increase", "boost", "hoist", "heighten", "escalate"],
        "random": ["arbitrary", "haphazard", "chance", "unplanned", "accidental", "casual"],
        "rapid": ["fast", "quick", "swift", "speedy", "brisk", "hasty", "prompt", "fleet"],
        "rare": ["uncommon", "unusual", "scarce", "exceptional", "infrequent", "unique", "precious"],
        "reach": ["arrive", "attain", "achieve", "get to", "extend", "stretch", "access"],
        "ready": ["prepared", "set", "equipped", "primed", "willing", "available", "fit"],
        "real": ["genuine", "authentic", "actual", "true", "legitimate", "valid", "original"],
        "realize": ["understand", "recognize", "grasp", "comprehend", "perceive", "discover", "achieve"],
        "reasonable": ["fair", "sensible", "rational", "logical", "moderate", "practical", "sound"],
        "receive": ["get", "obtain", "accept", "collect", "acquire", "take", "gain"],
        "recognize": ["identify", "acknowledge", "know", "realize", "detect", "spot", "appreciate"],
        "recommend": ["suggest", "advise", "propose", "advocate", "endorse", "urge", "prescribe"],
        "recover": ["heal", "recuperate", "regain", "reclaim", "restore", "bounce back"],
        "reduce": ["decrease", "lower", "diminish", "cut", "lessen", "shrink", "minimize", "trim"],
        "reflect": ["ponder", "contemplate", "consider", "think", "meditate", "mirror", "show"],
        "refuse": ["decline", "reject", "deny", "rebuff", "dismiss", "turn down", "spurn"],
        "regard": ["consider", "view", "see", "respect", "esteem", "attention", "concern"],
        "regret": ["lament", "mourn", "deplore", "rue", "repent", "bemoan", "sorrow"],
        "reject": ["refuse", "decline", "deny", "dismiss", "repudiate", "turn down", "spurn"],
        "relate": ["connect", "associate", "link", "pertain", "correspond", "apply", "concern"],
        "release": ["free", "liberate", "discharge", "let go", "publish", "issue", "launch"],
        "relevant": ["pertinent", "applicable", "related", "appropriate", "fitting", "suitable"],
        "reliable": ["dependable", "trustworthy", "consistent", "faithful", "stable", "solid"],
        "reluctant": ["hesitant", "unwilling", "disinclined", "resistant", "unenthusiastic", "wary"],
        "remain": ["stay", "continue", "persist", "endure", "linger", "last", "survive"],
        "remark": ["comment", "observe", "note", "mention", "state", "say", "point out"],
        "remarkable": ["notable", "outstanding", "extraordinary", "impressive", "exceptional", "striking"],
        "remedy": ["cure", "fix", "solution", "treatment", "antidote", "answer", "corrective"],
        "remember": ["recall", "recollect", "reminisce", "recognize", "retain", "commemorate"],
        "remote": ["distant", "faraway", "isolated", "secluded", "removed", "outlying"],
        "remove": ["eliminate", "take away", "discard", "extract", "delete", "withdraw", "strip"],
        "repair": ["fix", "mend", "restore", "patch", "overhaul", "renovate", "service"],
        "replace": ["substitute", "swap", "exchange", "succeed", "displace", "supplant"],
        "reply": ["respond", "answer", "react", "retort", "acknowledge", "counter"],
        "request": ["ask", "appeal", "petition", "demand", "seek", "solicit", "inquire"],
        "require": ["need", "demand", "necessitate", "call for", "compel", "mandate", "expect"],
        "resemble": ["look like", "mirror", "echo", "match", "parallel", "simulate"],
        "resist": ["oppose", "defy", "withstand", "refuse", "reject", "fight", "repel"],
        "resolve": ["settle", "solve", "determine", "fix", "decide", "conclude", "address"],
        "respect": ["esteem", "admire", "honor", "regard", "value", "appreciate", "revere"],
        "respond": ["reply", "answer", "react", "acknowledge", "retort", "counter"],
        "restore": ["repair", "renew", "revive", "recover", "rebuild", "reinstate", "return"],
        "restrain": ["hold back", "control", "limit", "curb", "check", "contain", "suppress"],
        "restrict": ["limit", "confine", "restrain", "constrain", "curb", "regulate", "control"],
        "result": ["outcome", "consequence", "effect", "product", "conclusion", "upshot"],
        "retain": ["keep", "hold", "maintain", "preserve", "save", "store", "reserve"],
        "reveal": ["disclose", "expose", "uncover", "show", "display", "divulge", "unveil"],
        "rich": ["wealthy", "affluent", "prosperous", "well-off", "loaded", "opulent", "abundant"],
        "rigid": ["stiff", "inflexible", "firm", "strict", "unyielding", "hard", "fixed"],
        "risk": ["danger", "hazard", "threat", "peril", "chance", "gamble", "jeopardy"],
        "rival": ["competitor", "opponent", "adversary", "challenger", "contender", "enemy"],
        "robust": ["strong", "sturdy", "tough", "vigorous", "resilient", "healthy", "solid"],
        "rough": ["coarse", "rugged", "uneven", "bumpy", "jagged", "harsh", "crude"],
        "rude": ["impolite", "discourteous", "disrespectful", "insolent", "offensive", "uncivil"],
        "ruin": ["destroy", "wreck", "devastate", "damage", "spoil", "demolish", "shatter"],
        "rule": ["govern", "regulation", "law", "principle", "guideline", "standard", "norm"],
        "run": ["sprint", "dash", "race", "jog", "rush", "gallop", "hurry", "operate"],
        "ruthless": ["merciless", "cruel", "heartless", "brutal", "pitiless", "relentless", "cold-blooded"],

        // S
        "sad": ["unhappy", "sorrowful", "melancholy", "gloomy", "depressed", "miserable", "downcast"],
        "safe": ["secure", "protected", "sheltered", "guarded", "harmless", "sound", "intact"],
        "satisfy": ["please", "fulfill", "content", "gratify", "meet", "appease", "quench"],
        "save": ["rescue", "preserve", "conserve", "store", "reserve", "protect", "keep"],
        "say": ["state", "declare", "express", "utter", "announce", "proclaim", "assert", "remark"],
        "scared": ["afraid", "frightened", "terrified", "fearful", "alarmed", "panicked", "startled"],
        "scatter": ["disperse", "spread", "distribute", "disseminate", "strew", "sprinkle"],
        "secret": ["hidden", "confidential", "private", "covert", "concealed", "classified", "discreet"],
        "secure": ["safe", "protected", "stable", "firm", "obtain", "fasten", "assured"],
        "seek": ["search", "look for", "pursue", "hunt", "quest", "strive", "aim"],
        "select": ["choose", "pick", "opt", "decide on", "prefer", "designate", "elect"],
        "send": ["dispatch", "transmit", "deliver", "forward", "ship", "convey", "mail"],
        "separate": ["divide", "split", "detach", "isolate", "disconnect", "part", "sever"],
        "serious": ["grave", "solemn", "severe", "critical", "earnest", "significant", "weighty"],
        "serve": ["help", "assist", "aid", "attend", "cater", "supply", "provide"],
        "settle": ["resolve", "decide", "establish", "arrange", "conclude", "determine", "fix"],
        "severe": ["harsh", "strict", "extreme", "intense", "serious", "grave", "stern"],
        "sharp": ["keen", "acute", "pointed", "fine", "incisive", "piercing", "precise"],
        "shelter": ["cover", "protection", "refuge", "haven", "sanctuary", "shield", "hideout"],
        "shift": ["change", "move", "switch", "transfer", "alter", "adjust", "transition"],
        "shine": ["glow", "gleam", "sparkle", "radiate", "beam", "glitter", "shimmer"],
        "shock": ["surprise", "stun", "startle", "astound", "horrify", "jolt", "dismay"],
        "short": ["brief", "concise", "compact", "small", "little", "abbreviated", "quick"],
        "show": ["display", "exhibit", "demonstrate", "present", "reveal", "indicate", "illustrate"],
        "shut": ["close", "seal", "lock", "fasten", "secure", "slam", "block"],
        "shy": ["timid", "bashful", "reserved", "introverted", "modest", "retiring", "meek"],
        "significant": ["important", "meaningful", "notable", "major", "substantial", "considerable"],
        "silent": ["quiet", "mute", "still", "hushed", "soundless", "noiseless", "speechless"],
        "silly": ["foolish", "ridiculous", "absurd", "goofy", "frivolous", "childish", "nonsensical"],
        "similar": ["alike", "comparable", "resembling", "analogous", "parallel", "related", "akin"],
        "simple": ["easy", "plain", "basic", "elementary", "uncomplicated", "straightforward", "clear"],
        "sincere": ["genuine", "honest", "heartfelt", "earnest", "truthful", "authentic", "real"],
        "skeptical": ["doubtful", "suspicious", "cynical", "questioning", "distrustful", "wary"],
        "slender": ["slim", "thin", "lean", "slight", "narrow", "svelte", "willowy"],
        "slow": ["unhurried", "leisurely", "gradual", "sluggish", "plodding", "measured", "deliberate"],
        "small": ["tiny", "little", "miniature", "compact", "petite", "minute", "modest", "slight"],
        "smart": ["intelligent", "clever", "bright", "brilliant", "sharp", "astute", "quick-witted"],
        "smooth": ["even", "flat", "sleek", "polished", "silky", "glossy", "seamless"],
        "soothe": ["calm", "comfort", "ease", "relieve", "pacify", "settle", "reassure"],
        "sophisticated": ["refined", "elegant", "cultured", "worldly", "complex", "advanced", "polished"],
        "sorrow": ["grief", "sadness", "woe", "heartache", "anguish", "mourning", "despair"],
        "special": ["unique", "particular", "exceptional", "distinctive", "remarkable", "extraordinary"],
        "specific": ["particular", "precise", "exact", "definite", "explicit", "detailed", "clear"],
        "splendid": ["magnificent", "glorious", "superb", "grand", "excellent", "brilliant", "wonderful"],
        "spontaneous": ["impulsive", "unplanned", "natural", "instinctive", "impromptu", "unrehearsed"],
        "stable": ["steady", "secure", "firm", "solid", "constant", "reliable", "balanced"],
        "start": ["begin", "commence", "initiate", "launch", "open", "embark", "originate", "kick off"],
        "steady": ["stable", "constant", "consistent", "firm", "reliable", "even", "uniform"],
        "stern": ["strict", "severe", "firm", "harsh", "rigid", "austere", "serious"],
        "stimulate": ["excite", "inspire", "motivate", "encourage", "arouse", "provoke", "trigger"],
        "stop": ["halt", "cease", "pause", "quit", "end", "terminate", "discontinue", "suspend"],
        "story": ["tale", "narrative", "account", "chronicle", "anecdote", "legend", "report"],
        "strange": ["odd", "unusual", "peculiar", "weird", "bizarre", "curious", "mysterious", "eccentric"],
        "strength": ["power", "force", "might", "vigor", "energy", "toughness", "resilience"],
        "strict": ["stern", "rigid", "harsh", "severe", "firm", "stringent", "rigorous"],
        "strong": ["powerful", "sturdy", "robust", "muscular", "tough", "mighty", "resilient", "vigorous"],
        "struggle": ["fight", "battle", "strive", "labor", "wrestle", "contend", "grapple"],
        "stubborn": ["obstinate", "headstrong", "persistent", "determined", "unyielding", "defiant"],
        "stupid": ["foolish", "dumb", "idiotic", "senseless", "brainless", "absurd", "unintelligent"],
        "submit": ["surrender", "yield", "present", "offer", "propose", "comply", "defer"],
        "substantial": ["significant", "considerable", "sizable", "large", "ample", "major", "solid"],
        "substitute": ["replace", "swap", "exchange", "alternate", "stand-in", "proxy", "surrogate"],
        "succeed": ["prosper", "thrive", "triumph", "prevail", "achieve", "flourish", "accomplish"],
        "sufficient": ["enough", "adequate", "ample", "satisfactory", "plenty", "suitable"],
        "suggest": ["propose", "recommend", "advise", "hint", "imply", "indicate", "offer"],
        "suitable": ["appropriate", "fitting", "proper", "right", "apt", "relevant", "adequate"],
        "superior": ["better", "higher", "greater", "finer", "premium", "excellent", "outstanding"],
        "supply": ["provide", "furnish", "deliver", "offer", "give", "stock", "distribute"],
        "support": ["help", "assist", "back", "uphold", "sustain", "aid", "encourage", "endorse"],
        "suppress": ["repress", "restrain", "stifle", "silence", "quash", "subdue", "squash"],
        "sure": ["certain", "confident", "positive", "definite", "convinced", "assured", "clear"],
        "surplus": ["excess", "extra", "remainder", "surplus", "overflow", "leftover", "spare"],
        "surprise": ["astonish", "amaze", "startle", "shock", "stun", "astound", "catch off guard"],
        "surrender": ["yield", "submit", "give up", "capitulate", "concede", "relinquish"],
        "survive": ["endure", "outlast", "persist", "withstand", "last", "weather", "overcome"],
        "suspect": ["doubt", "distrust", "question", "mistrust", "suppose", "guess", "believe"],
        "sustain": ["maintain", "support", "uphold", "preserve", "nourish", "keep", "continue"],
        "swift": ["fast", "quick", "rapid", "speedy", "prompt", "fleet", "hasty"],
        "symbol": ["sign", "emblem", "icon", "representation", "mark", "token", "figure"],
        "sympathy": ["compassion", "empathy", "pity", "understanding", "concern", "condolence"],

        // T
        "take": ["grab", "seize", "acquire", "obtain", "capture", "collect", "snatch", "accept"],
        "talent": ["skill", "gift", "ability", "aptitude", "flair", "knack", "genius"],
        "talk": ["speak", "converse", "discuss", "chat", "communicate", "dialogue", "tell"],
        "teach": ["instruct", "educate", "train", "tutor", "coach", "guide", "mentor"],
        "tedious": ["boring", "dull", "tiresome", "monotonous", "wearisome", "dreary", "laborious"],
        "tell": ["inform", "notify", "reveal", "disclose", "communicate", "announce", "relate"],
        "temporary": ["brief", "short-term", "interim", "provisional", "transient", "fleeting"],
        "tender": ["gentle", "soft", "kind", "delicate", "affectionate", "caring", "sensitive"],
        "terminate": ["end", "stop", "conclude", "finish", "cease", "close", "cancel", "discontinue"],
        "terrible": ["awful", "dreadful", "horrible", "atrocious", "appalling", "ghastly", "horrendous"],
        "terrify": ["frighten", "scare", "horrify", "alarm", "petrify", "intimidate", "shock"],
        "thick": ["dense", "heavy", "bulky", "solid", "stout", "broad", "wide"],
        "thin": ["slender", "slim", "lean", "narrow", "slight", "skinny", "fine"],
        "think": ["consider", "ponder", "reflect", "contemplate", "reason", "deliberate", "believe"],
        "thorough": ["complete", "comprehensive", "detailed", "exhaustive", "meticulous", "careful"],
        "threaten": ["menace", "intimidate", "endanger", "warn", "bully", "jeopardize"],
        "thrive": ["prosper", "flourish", "bloom", "succeed", "grow", "boom", "blossom"],
        "tidy": ["neat", "orderly", "organized", "clean", "trim", "shipshape", "immaculate"],
        "tight": ["snug", "firm", "taut", "secure", "compact", "constricted", "narrow"],
        "tiny": ["small", "miniature", "minute", "little", "microscopic", "petite", "wee"],
        "tired": ["exhausted", "fatigued", "weary", "drained", "spent", "worn out", "sleepy"],
        "tolerate": ["endure", "bear", "accept", "permit", "allow", "put up with", "withstand"],
        "top": ["peak", "summit", "pinnacle", "apex", "crest", "crown", "zenith", "height"],
        "total": ["complete", "entire", "whole", "full", "absolute", "overall", "sum"],
        "touch": ["feel", "handle", "contact", "tap", "brush", "stroke", "graze"],
        "tough": ["hard", "difficult", "strong", "resilient", "durable", "sturdy", "rugged"],
        "tradition": ["custom", "practice", "convention", "ritual", "heritage", "culture"],
        "tranquil": ["calm", "peaceful", "serene", "quiet", "still", "placid", "restful"],
        "transform": ["change", "convert", "alter", "modify", "reshape", "revolutionize", "overhaul"],
        "tremendous": ["enormous", "huge", "immense", "massive", "vast", "colossal", "extraordinary"],
        "trivial": ["insignificant", "minor", "petty", "unimportant", "trifling", "negligible"],
        "trouble": ["problem", "difficulty", "issue", "hardship", "distress", "complication", "predicament"],
        "true": ["real", "genuine", "accurate", "correct", "authentic", "valid", "factual", "honest"],
        "trust": ["believe", "rely on", "depend on", "faith", "confidence", "count on"],
        "try": ["attempt", "endeavor", "strive", "effort", "undertake", "venture", "seek"],
        "turmoil": ["chaos", "upheaval", "disorder", "confusion", "commotion", "turbulence", "unrest"],

        // U
        "ugly": ["unattractive", "hideous", "unsightly", "grotesque", "repulsive", "homely", "dreadful"],
        "ultimate": ["final", "supreme", "utmost", "greatest", "highest", "paramount", "best"],
        "unanimous": ["united", "unified", "agreed", "harmonious", "collective", "universal"],
        "uncertain": ["unsure", "doubtful", "undecided", "hesitant", "ambiguous", "unclear", "vague"],
        "understand": ["comprehend", "grasp", "perceive", "realize", "fathom", "appreciate", "get"],
        "unfair": ["unjust", "biased", "inequitable", "partial", "one-sided", "discriminatory"],
        "unfortunate": ["unlucky", "regrettable", "sad", "tragic", "deplorable", "lamentable"],
        "unhappy": ["sad", "miserable", "sorrowful", "discontented", "dejected", "gloomy", "depressed"],
        "uniform": ["consistent", "standard", "identical", "regular", "even", "homogeneous"],
        "unique": ["distinctive", "singular", "one-of-a-kind", "rare", "exceptional", "special"],
        "unite": ["join", "combine", "merge", "connect", "fuse", "consolidate", "unify"],
        "unusual": ["rare", "uncommon", "extraordinary", "strange", "peculiar", "unique", "atypical"],
        "update": ["revise", "refresh", "modernize", "upgrade", "renew", "amend", "improve"],
        "uphold": ["support", "maintain", "sustain", "defend", "preserve", "endorse", "champion"],
        "urgent": ["pressing", "critical", "crucial", "immediate", "imperative", "vital", "acute"],
        "use": ["utilize", "employ", "apply", "operate", "exercise", "exploit", "wield", "handle"],
        "useful": ["helpful", "practical", "beneficial", "valuable", "handy", "functional", "productive"],
        "usual": ["normal", "typical", "ordinary", "common", "regular", "standard", "customary"],

        // V
        "vague": ["unclear", "ambiguous", "indefinite", "imprecise", "fuzzy", "hazy", "nebulous"],
        "valid": ["legitimate", "sound", "reasonable", "justified", "genuine", "authentic", "legal"],
        "valuable": ["precious", "worthwhile", "important", "useful", "costly", "priceless", "prized"],
        "vanish": ["disappear", "fade", "evaporate", "dissolve", "go away", "recede"],
        "various": ["diverse", "different", "assorted", "multiple", "varied", "sundry", "several"],
        "vast": ["huge", "enormous", "immense", "expansive", "massive", "extensive", "boundless"],
        "versatile": ["adaptable", "flexible", "multi-talented", "resourceful", "all-round", "handy"],
        "very": ["extremely", "highly", "incredibly", "remarkably", "exceptionally", "immensely", "exceedingly"],
        "vibrant": ["lively", "dynamic", "energetic", "vivid", "spirited", "animated", "colorful"],
        "vicious": ["cruel", "savage", "brutal", "ferocious", "wicked", "malicious", "violent"],
        "vigorous": ["energetic", "strong", "robust", "dynamic", "active", "lively", "powerful"],
        "vital": ["essential", "crucial", "important", "critical", "necessary", "key", "indispensable"],
        "vivid": ["bright", "vibrant", "intense", "colorful", "striking", "graphic", "brilliant"],
        "voluntary": ["optional", "willing", "elective", "discretionary", "unpaid", "free"],
        "vulnerable": ["exposed", "defenseless", "susceptible", "unprotected", "at risk", "weak"],

        // W
        "walk": ["stroll", "stride", "march", "hike", "amble", "saunter", "wander", "trek"],
        "want": ["desire", "wish", "crave", "need", "yearn", "long for", "seek", "covet"],
        "warm": ["hot", "heated", "mild", "tepid", "cozy", "balmy", "cordial", "friendly"],
        "warn": ["alert", "caution", "advise", "notify", "forewarn", "inform", "signal"],
        "waste": ["squander", "misuse", "exhaust", "deplete", "discard", "fritter", "trash"],
        "watch": ["observe", "view", "monitor", "survey", "witness", "scrutinize", "see"],
        "weak": ["feeble", "frail", "fragile", "delicate", "flimsy", "powerless", "vulnerable"],
        "wealth": ["riches", "fortune", "prosperity", "affluence", "assets", "abundance", "money"],
        "wicked": ["evil", "sinful", "immoral", "corrupt", "villainous", "vile", "malicious"],
        "wide": ["broad", "vast", "extensive", "expansive", "spacious", "sweeping", "ample"],
        "wild": ["untamed", "feral", "savage", "fierce", "uncontrolled", "reckless", "frantic"],
        "willing": ["ready", "prepared", "eager", "inclined", "agreeable", "cooperative", "game"],
        "win": ["triumph", "prevail", "succeed", "conquer", "achieve", "earn", "secure"],
        "wise": ["smart", "sensible", "prudent", "sagacious", "astute", "judicious", "shrewd"],
        "withdraw": ["retreat", "pull out", "remove", "recede", "retract", "depart", "leave"],
        "wonderful": ["marvelous", "magnificent", "superb", "amazing", "fantastic", "splendid", "terrific"],
        "work": ["labor", "toil", "effort", "task", "job", "occupation", "employment", "function"],
        "worry": ["concern", "anxiety", "distress", "fret", "trouble", "unease", "stress"],
        "worth": ["value", "merit", "importance", "significance", "benefit", "usefulness"],
        "write": ["compose", "author", "draft", "pen", "record", "document", "inscribe"],
        "wrong": ["incorrect", "mistaken", "erroneous", "inaccurate", "false", "improper", "faulty"],

        // Y-Z
        "yearn": ["long", "crave", "desire", "pine", "ache", "hunger", "wish"],
        "yield": ["produce", "generate", "provide", "surrender", "concede", "give", "return"],
        "young": ["youthful", "juvenile", "immature", "junior", "teenage", "fresh", "new"],
        "zealous": ["passionate", "fervent", "enthusiastic", "eager", "ardent", "devoted", "keen"],
    ]
}
